---
# Playbook pour générer un rapport Excel à partir des données CMDB
# Usage: ansible-playbook -i inventory/dev/inventory.ini cmdb_report.yml --vault-password-file=.vault_pass

- name: Générer et envoyer le rapport CMDB
  hosts: localhost
  connection: local
  gather_facts: true
  become: false
  
  vars:
    # Configuration commune
    user_home: "{{ ansible_env.HOME }}"
    report_temp_dir: "{{ user_home }}/.cmdb_report_{{ ansible_date_time.epoch }}"
  
  roles:
    - role: python_venv
      vars:
        python_venv_path: "{{ user_home }}/.cmdb_venv"
        python_venv_extra_packages:
          - openpyxl>=3.0.0  # Nécessaire pour la génération de rapports Excel
          - jmespath>=0.10.0  # Nécessaire pour les filtres JSON
      tags:
        - setup
        - python
    
    - role: cmdb_report
      vars:
        cmdb_venv_path: "{{ user_home }}/.cmdb_venv"
        
        cmdb_repository:
          mode: "local"
          directory: "{{ user_home }}/.cmdb_inventory"
          fallback_directory: "{{ user_home }}/.cmdb_inventory_fallback"
          
        cmdb_report:
          filename: "cmdb_inventory_report_{{ ansible_date_time.date }}.xlsx"
          temp_dir: "{{ report_temp_dir }}"
          max_age_days: 7
          
        cmdb_email:
          enabled: false
          smtp:
            host: "{{ vault_smtp_host | default('smtp.example.com') }}"
            port: "{{ vault_smtp_port | default(25) }}"
            use_tls: "{{ vault_smtp_use_tls | default(false) }}"
            use_ssl: "{{ vault_smtp_use_ssl | default(false) }}"
            username: "{{ vault_smtp_username | default('') }}"
            password: "{{ vault_smtp_password | default('') }}"
          from: "{{ vault_smtp_from | default('cmdb-report@example.com') }}"
          to: "{{ vault_smtp_recipients | default(['admin@example.com']) }}"
          subject: "Rapport d'inventaire CMDB - {{ ansible_date_time.date }}"
          body_type: "html"
          attach_report: true
      tags:
        - report