---
# tasks/generate_excel.yml - Génération du rapport Excel

# Création du répertoire pour l'exécution du script Python
- name: (generate_excel) Créer le répertoire pour l'exécution du script
  file:
    path: "{{ cmdb_report.temp_dir }}/python"
    state: directory
    mode: '0755'
  delegate_to: "{{ cmdb_manager_host }}"
  tags:
    - generate
    - setup

# Créer la configuration pour le script Python
- name: (generate_excel) Créer la configuration pour la génération du rapport Excel
  template:
    src: report_config.j2
    dest: "{{ cmdb_report.temp_dir }}/report_config.json"
  delegate_to: "{{ cmdb_manager_host }}"
  tags:
    - generate
    - config

# Créer un environnement virtuel Python pour les dépendances
- name: (generate_excel) Créer un environnement virtuel Python
  command:
    cmd: "python3 -m venv {{ cmdb_report.temp_dir }}/venv"
    creates: "{{ cmdb_report.temp_dir }}/venv/bin/python"
  delegate_to: "{{ cmdb_manager_host }}"
  tags:
    - generate
    - venv

# Installer les dépendances Python requises dans l'environnement virtuel
- name: (generate_excel) Installer les dépendances Python requises dans l'environnement virtuel
  pip:
    name:
      - openpyxl>=3.0.0
      - jmespath>=0.10.0
    state: present
    virtualenv: "{{ cmdb_report.temp_dir }}/venv"
  delegate_to: "{{ cmdb_manager_host }}"
  tags:
    - generate
    - dependencies

# Copier le script Python depuis les files du rôle
- name: (generate_excel) Copier le script Python pour la génération du rapport Excel
  copy:
    src: generate_excel.py
    dest: "{{ cmdb_report.temp_dir }}/generate_excel.py"
    mode: '0755'
  delegate_to: "{{ cmdb_manager_host }}"
  tags:
    - generate
    - script

# Exécuter le script Python pour générer le rapport Excel en utilisant l'environnement virtuel
- name: (generate_excel) Générer le rapport Excel
  command:
    cmd: "{{ cmdb_report.temp_dir }}/venv/bin/python {{ cmdb_report.temp_dir }}/generate_excel.py {{ cmdb_report.temp_dir }}/report_config.json"
    chdir: "{{ cmdb_report.temp_dir }}"
  delegate_to: "{{ cmdb_manager_host }}"
  register: excel_generation
  failed_when: excel_generation.rc != 0
  changed_when: true
  tags:
    - generate
    - execute

# Afficher le résultat de la génération
- name: (generate_excel) Afficher le résultat de la génération du rapport Excel
  debug:
    msg: "{{ excel_generation.stdout_lines }}"
  when: excel_generation.stdout_lines is defined and excel_generation.stdout_lines | length > 0
  tags:
    - generate
    - debug

# Enregistrer le chemin du fichier Excel pour l'envoi ultérieur par email
- name: (generate_excel) Enregistrer le chemin du fichier Excel
  set_fact:
    cmdb_report_excel_path: "{{ cmdb_report.temp_dir }}/{{ cmdb_report.filename }}"
  tags:
    - generate
    - path