---
# tasks file for roles/cmdb_report

# Détermination du serveur repository (AVANT la validation)
- name: (main) Déterminer le mode de repository
  set_fact:
    cmdb_repository_mode: "{{ cmdb_repository.mode | default('local') }}"
  tags:
    - always

- name: (main) Déterminer le serveur manager
  set_fact:
    cmdb_manager_host: >-
      {% if cmdb_repository_mode == 'manager' and cmdb_repository.manager_group is defined %}
        {% if cmdb_repository.manager_group in groups and groups[cmdb_repository.manager_group] | length > 0 %}
          {{ groups[cmdb_repository.manager_group][0] }}
        {% else %}
          localhost
        {% endif %}
      {% else %}
        localhost
      {% endif %}
  tags:
    - always

- name: (main) Afficher les informations du repository
  debug:
    msg: 
      - "Mode repository: {{ cmdb_repository_mode }}"
      - "Serveur repository: {{ cmdb_manager_host }}"
      - "Répertoire des rapports: {{ cmdb_repository.directory }}/reports"
  tags:
    - always
    - debug

# Validation des prérequis (APRÈS la définition des variables critiques)
- name: (main) Inclusion des tâches de validation
  include_tasks: validate.yml
  tags:
    - always
    - validate

# Collecte et traitement des données JSON
- name: (main) Inclusion des tâches de collecte de données
  include_tasks: collect_data.yml
  tags:
    - always
    - collect

# Vérifier si des données ont été collectées
- name: (main) Vérifier si des données ont été collectées
  debug:
    msg: >-
      {% if cmdb_data is defined and cmdb_data | length > 0 %}
      {{ cmdb_data | length }} serveurs ont été chargés pour le rapport
      {% else %}
      Aucune donnée n'a été collectée pour le rapport
      {% endif %}
  tags:
    - always
    - check

# Génération du rapport Excel
- name: (main) Inclusion des tâches de génération du rapport Excel
  include_tasks: generate_excel.yml
  when: cmdb_data is defined and cmdb_data | length > 0
  tags:
    - always
    - generate
    - excel

- name: (main) Inclusion des tâches de débogage
  include_tasks: debug_tasks.yml
  tags:
    - never
    - debug

# Envoi par email
- name: (main) Inclusion des tâches d'envoi par email
  include_tasks: send_email.yml
  when: 
    - cmdb_email.enabled | bool
    - cmdb_report_excel_path is defined
  tags:
    - always
    - email
    - send

# Copier le rapport Excel vers le serveur repository si le mode est manager
- name: (main) Copier le rapport Excel vers le serveur repository
  copy:
    src: "{{ cmdb_report_excel_path }}"
    dest: "{{ cmdb_repository_actual_dir | default(cmdb_repository.directory) }}/reports/"
  delegate_to: "{{ cmdb_manager_host }}"
  when: 
    - cmdb_repository_mode == 'manager'
    - cmdb_manager_host != 'localhost'
    - cmdb_report_excel_path is defined
  register: copy_result
  ignore_errors: true
  tags:
    - always
    - copy

# Afficher le résultat de la copie
- name: (main) Afficher le résultat de la copie
  debug:
    msg: >-
      {% if copy_result is defined and copy_result is success %}
      Rapport Excel copié avec succès sur le serveur repository {{ cmdb_manager_host }}
      {% elif copy_result is defined %}
      Échec de la copie du rapport Excel sur le serveur repository
      {% endif %}
  when: 
    - cmdb_repository_mode == 'manager'
    - cmdb_manager_host != 'localhost'
    - cmdb_report_excel_path is defined
  tags:
    - always
    - copy

# Nettoyage
- name: (main) Nettoyer les fichiers temporaires
  file:
    path: "{{ cmdb_report.temp_dir }}"
    state: absent
  delegate_to: "{{ cmdb_manager_host }}"
  ignore_errors: true
  when: 
    - cmdb_report.temp_dir is defined 
    - cmdb_report.temp_dir | regex_search('^/tmp/.*')
  tags:
    - always
    - cleanup

# Résumé
- name: (main) Résumé de l'exécution
  debug:
    msg: >-
      Rapport CMDB généré avec succès!
      {% if cmdb_report_excel_path is defined %}
      - Fichier: {{ cmdb_report_excel_path | basename }}
      - Serveurs inclus: {{ cmdb_data | length }}
      - Emplacement local: {{ cmdb_report_excel_path }}
      {% if cmdb_repository_mode == 'manager' and cmdb_manager_host != 'localhost' %}
      - Copié sur: {{ cmdb_manager_host }}:{{ cmdb_repository_actual_dir | default(cmdb_repository.directory) }}/reports/
      {% endif %}
      {% if cmdb_email.enabled | bool %}
      - Envoyé par email à: {{ cmdb_email.to | join(', ') }}
      {% endif %}
      {% endif %}
  when: cmdb_report_excel_path is defined
  tags:
    - always
    - summary