---
# tasks file for roles/cmdb_report

# Détermination du serveur repository (AVANT la validation)
- name: Déterminer le mode de repository
  set_fact:
    cmdb_repository_mode: "{{ cmdb_repository.mode | default('local') }}"
  tags:
    - always

- name: Déterminer le serveur manager
  set_fact:
    cmdb_manager_host: >-
      {% if cmdb_repository_mode == 'manager' and cmdb_repository.manager_group is defined %}
        {% if cmdb_repository.manager_group in groups and groups[cmdb_repository.manager_group] | length > 0 %}
          {{ groups[cmdb_repository.manager_group][0] }}
        {% else %}
          localhost
        {% endif %}
      {% else %}
        localhost
      {% endif %}
  tags:
    - always

- name: Afficher les informations du repository
  debug:
    msg: 
      - "Mode repository: {{ cmdb_repository_mode }}"
      - "Serveur repository: {{ cmdb_manager_host }}"
      - "Répertoire des rapports: {{ cmdb_repository.directory }}/reports"
  tags:
    - always
    - debug

# Validation des prérequis (APRÈS la définition des variables critiques)
- name: Inclusion des tâches de validation
  include_tasks: validate.yml
  tags:
    - always
    - validate

# Collecte et traitement des données JSON
- name: Inclusion des tâches de collecte de données
  include_tasks: collect_data.yml
  tags:
    - always
    - collect

# Génération du rapport Excel
- name: Inclusion des tâches de génération du rapport Excel
  include_tasks: generate_excel.yml
  when: cmdb_files is defined and cmdb_files|length > 0
  tags:
    - always
    - generate
    - excel

# Envoi par email
- name: Inclusion des tâches d'envoi par email
  include_tasks: send_email.yml
  when: 
    - cmdb_email.enabled | bool
    - cmdb_report_excel_path is defined
  tags:
    - always
    - email
    - send

# Nettoyage
- name: Nettoyer les fichiers temporaires
  file:
    path: "{{ cmdb_report.temp_dir }}"
    state: absent
  delegate_to: localhost
  become: false
  ignore_errors: true
  tags:
    - always
    - cleanup